<?php
/**
 * Created by PhpStorm.
 * User: Alex
 * Date: 09.06.2019
 * Time: 17:31
 */

class AboutController extends Controller
{
    public function generateView()
    {
        $view = 'about';
        parent::createView($view); // TODO: Change the autogenerated stub
    }
}