<?php
/**
 * Created by PhpStorm.
 * User: Alex
 * Date: 09.06.2019
 * Time: 17:32
 */

class InterestsController extends Controller
{
    public function generateView()
    {
        $view = 'interests';
        parent::createView($view); // TODO: Change the autogenerated stub
    }
}