<?php
/**
 * Created by PhpStorm.
 * User: Alex
 * Date: 09.06.2019
 * Time: 17:33
 */

class TestController extends Controller
{
    public function generateView()
    {
        $view = 'test';
        parent::createView($view); // TODO: Change the autogenerated stub
    }
}